### ISSUE TITLE
No popup when click extension button

### ISSUE THREAD

**Issue by tfx2001** [huhu/cpp-search-extension#16]
When I click extension button, there is no popup open.

- **Version**: `0.3.1`
- **Browser**: `Edge 104.0.1293.63`

**Comment by SteveLauC** [comment]
Same here. Try to enable offline mode following the [tutorial](https://cpp.extension.sh/#offline-mode), finding the popup does not show up at all.
* Version: `0.3.1`
* Browser: `Chrome 104.0.5112.101 (Official Build) unknown (64-bit) (flatpak version)`
* OS: Fedora 36

**Comment by Folyd** [comment]
Thanks for the feedback. Try to open `chrome-extension://ifpcmhciihicaljnhgobnhoehoabidhd/popup/index.html`. @tfx2001 @SteveLauC

**Comment by SteveLauC** [comment]
> Thanks for the feedback. Try to open `chrome-extension://ifpcmhciihicaljnhgobnhoehoabidhd/popup/index.html`. @tfx2001 @SteveLauC

Thanks for the quick response. This works in chrome.

**Comment by tfx2001** [comment]
> Thanks for the feedback. Try to open `chrome-extension://ifpcmhciihicaljnhgobnhoehoabidhd/popup/index.html`. @tfx2001 @SteveLauC

It works for me too.

**Comment by Arteiimis** [comment]
> Thanks for the feedback. Try to open `chrome-extension://ifpcmhciihicaljnhgobnhoehoabidhd/popup/index.html`. @tfx2001 @SteveLauC
what about edge?

**Comment by tfx2001** [comment]
> what about edge?

Just directly open the link mentioned above or try this `extension://ifpcmhciihicaljnhgobnhoehoabidhd/popup/index.html` @Arteiimis

**Comment by Folyd** [comment]
Fixed in v0.4.0
