### ISSUE TITLE
[Feature request] Option to config cppreference language

### ISSUE THREAD

**Issue by chawyehsu** [huhu/cpp-search-extension#2]
The extension uses en.cppreference.com as the doc source by default, it would be great it's configurable so users can switch to other languages of cppreference.

**Comment by Folyd** [comment]
Hey @chawyehsu, what do you mean `other languages of cppreference`?

**Comment by chawyehsu** [comment]
Sorry I mean the translations of cppreference like https://zh.cppreference.com
![](https://user-images.githubusercontent.com/5764917/101110250-8f37a800-3613-11eb-808d-30d637c75846.png)

**Comment by Folyd** [comment]
Great suggestion. 👍 Added to milestone 0.2!

**Comment by Folyd** [comment]
Hi @chawyehsu, v0.2.0 has been released. I'll close this issue. If you have any further issues please file a new one.
