### ISSUE TITLE
POSIX page is outdated

### ISSUE THREAD

**Issue by h3xOo** [huhu/cpp-search-extension#26]
Right now `:posix` goes to `https://pubs.opengroup.org/onlinepubs/9699919799/`, while there's newer `https://pubs.opengroup.org/onlinepubs/9799919799/` (first 6 is changed to 7)

**Comment by Folyd** [comment]
Thanks for the feedback. Feel free to file a PR :) 
https://github.com/huhu/cpp-search-extension/blob/b96d6e622cf718329b7e1e086879572b7af66663/extension/command/posix.js#L30
