### ISSUE TITLE
how to use offline mode

### ISSUE THREAD

**Issue by manch1n** [huhu/cpp-search-extension#8]
I download the HTML offline archive and try to input the local path:C:\Users\manch\Desktop\FTP\html-book-20210212\reference\zh
But failed.

**Comment by Folyd** [comment]
Thanks for the feedback. Seems like we forgot to support the Windows-style path. https://github.com/huhu/cpp-search-extension/blob/master/extension/settings.js#L3

May your mind try the workaround?
https://cpp.extension.sh/faq/#caveats
